[package]
name = "vade-sidetree"
version = "0.0.3"
authors = ["evan GmbH"]
edition = "2018"
license-file = "LICENSE.txt"
description = "handling DIDs based on sidetree implementation"
readme = "README.md"
keywords = ["did", "ssi"]

[lib]
name = "vade_sidetree"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.31"
base64 = "0.13.0"
env_logger = "0.7.1"
regex = { version = "1.3.7" }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sidetree-client = { version = "0.1.2", path = "./sidetree-client" }
sha2 = "0.9.5"
vade = "0.1.0"

[dev-dependencies]
tokio = { version = "=1.7.1", features = ["macros", "rt-multi-thread"] }
serial_test = "0.5.1"
